# Generated by Django 3.2.9 on 2021-11-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_pi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='chefe_setor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('Compras', 'COMPRAS'), ('Administrativo', 'ADM'), ('Almoxarifado', 'ALMOX')], max_length=20),
        ),
    ]
